### ISSUE TITLE
cmd prompt ~ -staking=0/1  ,  and reservebalance

### ISSUE THREAD

**Issue by Tillkoeln** [FromHDDtoSSD/SorachanCoin-qt#1]
hello, 
is there any alternative to -staking=0 existing?  as far as i can see,  the command isnt existing. 

and ..  "reservebalance" crash the client when any digit gets added. "common usecase or ? " 
... let me know if there is any fix on the latest updates ...  later then v1.1.6"

**Comment by FromHDDtoSSD** [comment]
We have fixed with the latest version. thanks.
